# Generated by Django 6.0.4 on 2026-04-27 17:35

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='La GMAO open source', max_length=255, verbose_name='Titre Hero')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Sous-titre Hero')),
                ('hero_badge_text', models.CharField(default='v2.4 disponible', max_length=100, verbose_name='Texte du badge')),
                ('hero_primary_cta_text', models.CharField(default='Commencer', max_length=100, verbose_name='Texte bouton principal')),
                ('hero_secondary_cta_text', models.CharField(default='GitHub', max_length=100, verbose_name='Texte bouton secondaire')),
                ('hero_secondary_cta_url', models.URLField(default='https://github.com/mouedarbi/SMARTOPS.git', verbose_name='URL bouton secondaire')),
                ('terminal_title', models.CharField(default='terminal — installation rapide', max_length=100, verbose_name='Titre du terminal')),
                ('features_section_title', models.CharField(default='Fonctionnalités core', max_length=100, verbose_name='Titre de la section')),
                ('features_intro', wagtail.fields.RichTextField(blank=True, default='Tout ce dont la maintenance a besoin.', verbose_name='Introduction des fonctionnalités')),
                ('marketplace_section_title', models.CharField(default='Marketplace', max_length=100, verbose_name='Titre de la section')),
                ('marketplace_intro', wagtail.fields.RichTextField(blank=True, default='Modules Pro à la demande.', verbose_name='Introduction du Marketplace')),
                ('marketplace_view_all_text', models.CharField(default='Voir tous les modules →', max_length=100, verbose_name='Texte lien tout voir')),
                ('marketplace_empty_msg', models.CharField(default='Aucun module disponible pour le moment.', max_length=255, verbose_name='Message si vide')),
                ('packs_section_title', models.CharField(default='Offres groupées', max_length=100, verbose_name='Petit titre section')),
                ('packs_main_title', models.CharField(default='Packs de modules (Pay-once)', max_length=100, verbose_name='Grand titre section')),
                ('packs_subtitle', models.TextField(default='Équipez-vous au meilleur prix avec nos packs thématiques.', verbose_name='Sous-titre section')),
                ('packs_empty_msg', models.CharField(default='Aucune offre groupée disponible actuellement.', max_length=255, verbose_name='Message si vide')),
                ('github_title', models.CharField(default='100% open source. Vos données restent chez vous.', max_length=255, verbose_name='Titre section GitHub')),
                ('github_subtitle', models.TextField(default='Le cœur SmartOps Portal est sous licence MIT. Hébergez où vous voulez, modifiez librement, contribuez.', verbose_name='Sous-titre section GitHub')),
                ('github_cta_text', models.CharField(default='Voir sur GitHub', max_length=100, verbose_name='Texte bouton GitHub')),
                ('github_docs_text', models.CharField(default='Lire la documentation →', max_length=100, verbose_name='Texte lien documentation')),
                ('github_docs_url', models.CharField(default='/fr/content/', max_length=255, verbose_name='URL documentation')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content.homepage')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_homepage_feature')],
            },
        ),
        migrations.CreateModel(
            name='HomePageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.homepage')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_homepage_stat')],
            },
        ),
        migrations.CreateModel(
            name='HomePageTerminalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('line_type', models.CharField(choices=[('comment', 'Commentaire'), ('command', 'Commande'), ('success', 'Succès'), ('empty', 'Ligne vide')], default='command', max_length=20)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_lines', to='content.homepage')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_homepage_terminal')],
            },
        ),
    ]
