# Generated by Django 6.0.3 on 2026-03-31 11:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_intro',
            field=wagtail.fields.RichTextField(blank=True, default="Tout ce dont la maintenance a besoin, inclus d'emblée.", verbose_name='Introduction des fonctionnalités'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Téléchargez le cœur gratuitement sur GitHub. Étendez votre GMAO avec des modules professionnels : IoT, mobile, analytics, IA prédictive.', verbose_name='Sous-titre Hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default="La GMAO open source pour l'industrie moderne", max_length=255, verbose_name='Titre Hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='marketplace_intro',
            field=wagtail.fields.RichTextField(blank=True, default='Modules Pro à la demande. Achat unique, utilisation illimitée.', verbose_name='Introduction du Marketplace'),
        ),
    ]
