# Generated by Django 6.0.3 on 2026-04-04 12:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_homepage_body_remove_homepage_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('stats_strip', 11), ('terminal', 16), ('feature_grid', 22), ('github_cta', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre principal', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Sous-titre descriptif', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'v2.4 disponible — Licence MIT', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '⚡ Commencer gratuitement', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Voir sur GitHub', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'default': 'https://github.com/mouedarbi/SMARTOPS.git', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('badge_text', 2), ('primary_button_text', 3), ('secondary_button_text', 4), ('secondary_button_url', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ex: green, blue ou code Hex', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('value', 7), ('label', 7), ('color', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('stats', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'terminal — installation rapide'}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('comment', 'Commentaire (#)'), ('command', 'Commande ($)'), ('success', 'Succès (✓)'), ('empty', 'Ligne vide')]}), 14: ('wagtail.blocks.StructBlock', [[('type', 13), ('content', 7)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('lines', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': "Emoji ou nom d'icône"}), 19: ('wagtail.blocks.TextBlock', (), {}), 20: ('wagtail.blocks.StructBlock', [[('icon', 18), ('title', 7), ('description', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('title', 17), ('features', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'default': "Rejoignez l'aventure Open Source"}), 24: ('wagtail.blocks.TextBlock', (), {'default': 'Contribuez, forkz ou déployez simplement. SMARTOPS grandit grâce à sa communauté.'}), 25: ('wagtail.blocks.CharBlock', (), {'default': '2.4k'}), 26: ('wagtail.blocks.CharBlock', (), {'default': '450'}), 27: ('wagtail.blocks.StructBlock', [[('title', 23), ('subtitle', 24), ('stars_count', 25), ('forks_count', 26)]], {})}, null=True, verbose_name='Corps de la page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Téléchargez le cœur gratuitement sur GitHub. Étendez votre GMAO avec des modules professionnels : IoT, mobile, analytics, IA prédictive.', verbose_name='Sous-titre Hero (Fallback)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default="La GMAO open source pour l'industrie moderne", max_length=255, verbose_name='Titre Hero (Fallback)'),
        ),
    ]
