# Generated by Django 6.0.3 on 2026-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_homepage_body_alter_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Téléchargez le cœur gratuitement sur GitHub. Étendez votre GMAO avec des modules professionnels : IoT, mobile, analytics, IA prédictive.', verbose_name='Sous-titre Hero'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default="La GMAO open source pour l'industrie moderne", max_length=255, verbose_name='Titre Hero'),
        ),
    ]
