# Generated by Django 6.0.3 on 2026-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_homepage_body_alter_homepage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_badge_text',
            field=models.CharField(default='v2.4 disponible — Licence MIT', max_length=100, verbose_name='Texte du badge'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta_text',
            field=models.CharField(default='⚡ Commencer gratuitement', max_length=100, verbose_name='Texte bouton principal'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_text',
            field=models.CharField(default='Voir sur GitHub', max_length=100, verbose_name='Texte bouton secondaire'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_url',
            field=models.URLField(default='https://github.com/mouedarbi/SMARTOPS.git', verbose_name='URL bouton secondaire'),
        ),
    ]
