# Generated by Django 6.0.3 on 2026-04-04 21:50

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_homepage_hero_badge_text_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Téléchargez le cœur gratuitement sur GitHub. Étendez votre GMAO avec des modules professionnels.', verbose_name='Sous-titre Hero'),
        ),
        migrations.CreateModel(
            name='HomePageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=50, verbose_name='Valeur (ex: 2k+)')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé (ex: Installations)')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.homepage')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_homepage_stat')],
            },
        ),
    ]
