# Generated by Django 6.0.3 on 2026-04-04 22:11

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_homepage_hero_subtitle_homepagestat'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='terminal_title',
            field=models.CharField(default='terminal — installation rapide', max_length=100, verbose_name='Titre du terminal'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_intro',
            field=wagtail.fields.RichTextField(blank=True, default='Tout ce dont la maintenance a besoin.', verbose_name='Introduction des fonctionnalités'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_badge_text',
            field=models.CharField(default='v2.4 disponible', max_length=100, verbose_name='Texte du badge'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Téléchargez le cœur gratuitement sur GitHub.', verbose_name='Sous-titre Hero'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='marketplace_intro',
            field=wagtail.fields.RichTextField(blank=True, default='Modules Pro à la demande.', verbose_name='Introduction du Marketplace'),
        ),
        migrations.CreateModel(
            name='HomePageTerminalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('line_type', models.CharField(choices=[('comment', 'Commentaire (#)'), ('command', 'Commande ($)'), ('success', 'Succès (✓)'), ('empty', 'Ligne vide')], default='command', max_length=20, verbose_name='Type de ligne')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='Contenu')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_lines', to='content.homepage')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_homepage_terminal')],
            },
        ),
    ]
