# Generated by Django 6.0.3 on 2026-04-04 22:16

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_homepage_terminal_title_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='features_section_title',
            field=models.CharField(default='Fonctionnalités core', max_length=100, verbose_name='Titre de la section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_primary_cta_text',
            field=models.CharField(default='Commencer', max_length=100, verbose_name='Texte bouton principal'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_secondary_cta_text',
            field=models.CharField(default='GitHub', max_length=100, verbose_name='Texte bouton secondaire'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='Sous-titre Hero'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='La GMAO open source', max_length=255, verbose_name='Titre Hero'),
        ),
        migrations.AlterField(
            model_name='homepagestat',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagestat',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homepageterminalline',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepageterminalline',
            name='line_type',
            field=models.CharField(choices=[('comment', 'Commentaire'), ('command', 'Commande'), ('success', 'Succès'), ('empty', 'Ligne vide')], default='command', max_length=20),
        ),
        migrations.CreateModel(
            name='HomePageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(help_text='Emoji ou texte (ex: 🔧)', max_length=50, verbose_name='Icône')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content.homepage')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_homepage_feature')],
            },
        ),
    ]
