# Generated by Django 6.0.3 on 2026-04-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_homepage_features_section_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='marketplace_empty_msg',
            field=models.CharField(default='Aucun module disponible pour le moment.', max_length=255, verbose_name='Message si vide'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='marketplace_section_title',
            field=models.CharField(default='Marketplace', max_length=100, verbose_name='Titre de la section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='marketplace_view_all_text',
            field=models.CharField(default='Voir tous les modules →', max_length=100, verbose_name='Texte lien tout voir'),
        ),
        migrations.AlterField(
            model_name='homepagefeature',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='Icône'),
        ),
    ]
