# Generated by Django 6.0.3 on 2026-04-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_homepage_marketplace_empty_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='packs_empty_msg',
            field=models.CharField(default='Aucune offre groupée disponible actuellement.', max_length=255, verbose_name='Message si vide'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='packs_main_title',
            field=models.CharField(default='Packs de modules (Pay-once)', max_length=100, verbose_name='Grand titre section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='packs_section_title',
            field=models.CharField(default='Offres groupées', max_length=100, verbose_name='Petit titre section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='packs_subtitle',
            field=models.TextField(default='Équipez-vous au meilleur prix avec nos packs thématiques.', verbose_name='Sous-titre section'),
        ),
        migrations.AlterField(
            model_name='homepagefeature',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepagefeature',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homepagefeature',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
