# Generated by Django 6.0.3 on 2026-04-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_homepage_packs_empty_msg_homepage_packs_main_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='github_docs_text',
            field=models.CharField(default='Lire la documentation →', max_length=100, verbose_name='Texte lien documentation'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='github_docs_url',
            field=models.CharField(default='/fr/content/', max_length=255, verbose_name='URL documentation'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='github_subtitle',
            field=models.TextField(default='Le cœur SmartOps Portal est sous licence MIT. Hébergez où vous voulez, modifiez librement, contribuez.', verbose_name='Sous-titre section GitHub'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='github_title',
            field=models.CharField(default='100% open source. Vos données restent chez vous.', max_length=255, verbose_name='Titre section GitHub'),
        ),
    ]
