# Generated by Django 6.0.3 on 2026-04-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_homepage_github_docs_text_homepage_github_docs_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='github_cta_text',
            field=models.CharField(default='Voir sur GitHub', max_length=100, verbose_name='Texte bouton GitHub'),
        ),
    ]
