# Generated by Django 6.0.3 on 2026-03-31 17:28

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='📦', help_text="Emoji ou nom d'icône Lucide", max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='CoreVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='Version du Cœur')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Version supportée')),
            ],
            options={
                'verbose_name': 'Version Core',
                'verbose_name_plural': 'Versions Core',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du module')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(help_text='Affichée sur les cartes du catalogue.', max_length=500, verbose_name='Description courte')),
                ('description', wagtail.fields.RichTextField(verbose_name='Description complète')),
                ('featured_image', models.ImageField(upload_to='modules/featured/', verbose_name='Image de mise en avant')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (Paiement unique)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='catalog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='ModuleScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='modules/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('module', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='catalog.module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='N° de version (ex: 1.2.0)')),
                ('release_date', models.DateField(verbose_name='Date de sortie')),
                ('changelog', models.TextField(blank=True, verbose_name='Notes de version')),
                ('file', models.FileField(upload_to='modules/packages/', verbose_name='Package (.zip / .tar.gz)')),
                ('min_core_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.coreversion', verbose_name='Version Core minimale requise')),
                ('module', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.module')),
            ],
            options={
                'verbose_name': 'Version de module',
                'verbose_name_plural': 'Versions de modules',
                'unique_together': {('module', 'version_number')},
            },
        ),
    ]
