# Generated by Django 6.0.3 on 2026-03-31 17:57

import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du pack')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(max_length=500, verbose_name='Description courte')),
                ('description', wagtail.fields.RichTextField(verbose_name='Description complète')),
                ('featured_image', models.ImageField(upload_to='bundles/featured/', verbose_name='Image du pack')),
                ('discount_mode', models.CharField(choices=[('PERCENTAGE', 'Remise en pourcentage sur le total'), ('FIXED', 'Prix fixe pour le pack (Ristourne manuelle)')], default='PERCENTAGE', max_length=20, verbose_name='Mode de remise')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Si mode Pourcentage: entrez 20 pour -20%. Si mode Prix Fixe: entrez le prix final.', max_digits=10, verbose_name='Valeur (Remise % ou Prix Fixe)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Laisser vide pour une activation immédiate.', null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, help_text='Laisser vide pour une durée illimitée.', null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('modules', modelcluster.fields.ParentalManyToManyField(related_name='bundles', to='catalog.module', verbose_name='Modules inclus')),
            ],
            options={
                'verbose_name': 'Pack de modules',
                'verbose_name_plural': 'Packs de modules',
            },
        ),
    ]
