# Generated by Django 6.0.4 on 2026-04-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='module',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description complète'),
        ),
        migrations.AddField(
            model_name='module',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description complète'),
        ),
        migrations.AddField(
            model_name='module',
            name='description_nl',
            field=models.TextField(null=True, verbose_name='Description complète'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom du module'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom du module'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom du module'),
        ),
        migrations.AddField(
            model_name='module',
            name='short_description_en',
            field=models.TextField(help_text='Affichée sur les cartes du catalogue.', max_length=500, null=True, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='module',
            name='short_description_fr',
            field=models.TextField(help_text='Affichée sur les cartes du catalogue.', max_length=500, null=True, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='module',
            name='short_description_nl',
            field=models.TextField(help_text='Affichée sur les cartes du catalogue.', max_length=500, null=True, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description complète'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description complète'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='description_nl',
            field=models.TextField(null=True, verbose_name='Description complète'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom du pack'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom du pack'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='name_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom du pack'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='short_description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='short_description_fr',
            field=models.TextField(max_length=500, null=True, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='short_description_nl',
            field=models.TextField(max_length=500, null=True, verbose_name='Description courte'),
        ),
    ]
