# Generated by Django 6.0.3 on 2026-04-04 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_modulebundle'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moduleversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='locale',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='category',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='module',
            name='locale',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='module',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='locale',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='modulescreenshot',
            name='locale',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='modulescreenshot',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='moduleversion',
            name='locale',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='moduleversion',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Slug unique pour la catégorie'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(help_text="Slug pour l'URL"),
        ),
        migrations.AlterField(
            model_name='modulebundle',
            name='slug',
            field=models.SlugField(help_text="Slug pour l'URL"),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('slug', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='modulebundle',
            unique_together={('slug', 'locale')},
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_catalog_category'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_catalog_module'),
        ),
        migrations.AddConstraint(
            model_name='modulebundle',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_catalog_bundle'),
        ),
        migrations.AddConstraint(
            model_name='modulescreenshot',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_catalog_screenshot'),
        ),
        migrations.AddConstraint(
            model_name='moduleversion',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_catalog_version'),
        ),
    ]
