# Generated by Django 6.0.4 on 2026-04-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_name_en_category_name_fr_category_name_nl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(help_text='Slug unique pour la catégorie', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(help_text='Slug unique pour la catégorie', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_nl',
            field=models.SlugField(help_text='Slug unique pour la catégorie', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slug_en',
            field=models.SlugField(help_text="Slug pour l'URL", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slug_fr',
            field=models.SlugField(help_text="Slug pour l'URL", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slug_nl',
            field=models.SlugField(help_text="Slug pour l'URL", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='slug_en',
            field=models.SlugField(help_text="Slug pour l'URL", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='slug_fr',
            field=models.SlugField(help_text="Slug pour l'URL", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modulebundle',
            name='slug_nl',
            field=models.SlugField(help_text="Slug pour l'URL", max_length=255, null=True, unique=True),
        ),
    ]
