# Generated by Django 6.0.4 on 2026-04-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_slug_en_category_slug_fr_category_slug_nl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleversion',
            name='max_core_version',
            field=models.ForeignKey(blank=True, help_text='Laissez vide si compatible avec toutes les versions futures.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_compatible_modules', to='catalog.coreversion', verbose_name='Version Core maximale (Optionnel)'),
        ),
        migrations.AlterField(
            model_name='moduleversion',
            name='min_core_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='min_compatible_modules', to='catalog.coreversion', verbose_name='Version Core minimale requise'),
        ),
    ]
