# Generated by Django 5.1.15 on 2026-07-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_moduleversion_max_core_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note (Étoiles)')),
                ('comment', models.TextField(verbose_name='Commentaire original')),
                ('comment_language', models.CharField(default='fr', max_length=5, verbose_name="Langue d'origine")),
                ('comment_fr', models.TextField(blank=True, null=True, verbose_name='Commentaire (FR)')),
                ('comment_en', models.TextField(blank=True, null=True, verbose_name='Commentaire (EN)')),
                ('comment_nl', models.TextField(blank=True, null=True, verbose_name='Commentaire (NL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.modulebundle', verbose_name='Pack')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.module', verbose_name='Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire et Note',
                'verbose_name_plural': 'Commentaires et Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
