# Generated by Django 5.1.15 on 2026-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='support_annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Laisser vide si ce module n'offre pas d'abonnement support/maintenance.", max_digits=10, null=True, verbose_name='Prix Support Annuel (€)'),
        ),
    ]
