# Generated by Django 5.1.15 on 2026-10-06 20:21

import catalog.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_module_support_annual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleversion',
            name='mobile_apk',
            field=models.FileField(blank=True, help_text='Uniquement pour le module SmartOps Mobile.', storage=catalog.storage.PrivateMediaStorage(), upload_to='mobile/', validators=[django.core.validators.FileExtensionValidator(['apk'])], verbose_name="APK de l'application mobile"),
        ),
    ]
