# Generated by Django 5.1.15 on 2026-09-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('nl', 'Nederlands')], default='fr', max_length=5, verbose_name='Langue préférée'),
        ),
    ]
