# Generated by Django 5.1.15 on 2026-10-03 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Particulier'), ('professional', 'Professionnel')], default='individual', editable=False, max_length=12, verbose_name='Type de compte'),
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('vat_number', models.CharField(max_length=14, verbose_name='Numéro de TVA')),
                ('street', models.CharField(max_length=255, verbose_name='Rue et numéro')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(max_length=100, verbose_name='Localité')),
                ('country', models.CharField(default='BE', editable=False, max_length=2, verbose_name='Pays')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Profil de facturation',
                'verbose_name_plural': 'Profils de facturation',
            },
        ),
    ]
