# Generated by Django 5.1.15 on 2026-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_site_name_smartops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='vat_number',
            field=models.CharField(max_length=30, verbose_name='Numéro de TVA'),
        ),
    ]
