# Generated by Django 5.1.15 on 2026-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='withdrawal_waiver_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentement de renonciation au droit de rétractation (Art. VI.53, 13° CDE)'),
        ),
    ]
