# Generated by Django 5.1.15 on 2026-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_withdrawal_waiver_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(choices=[('module', 'Module'), ('support', 'Support annuel')], default='module', max_length=20, verbose_name='Type de produit'),
        ),
    ]
