# Generated by Django 5.1.15 on 2026-09-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_orderitem_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant à rembourser manuellement via Stripe (droit de rétractation, art. VI.51 CDE). Remis à zéro une fois le remboursement traité.', max_digits=10, null=True, verbose_name='Remboursement dû (rétractation, support en cours)'),
        ),
    ]
