# Generated by Django 5.1.15 on 2026-09-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_order_refund_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('refund_pending', 'Remboursement à traiter'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
