# Generated by Django 5.1.15 on 2026-10-02 21:50

from django.db import migrations, models


def backfill_item_refunds(apps, schema_editor):
    """Reporte sur la ligne de support les remboursements consignés avant le détail par ligne.

    Jusqu'ici, seul le support pouvait être remboursé, et une seule ligne par commande.
    """
    Order = apps.get_model('payments', 'Order')
    for order in Order.objects.filter(refund_due_amount__isnull=False):
        items = list(order.items.filter(product_type='support'))
        if len(items) == 1:
            items[0].refund_due_amount = order.refund_due_amount
            items[0].refund_reason = 'withdrawal_support'
            items[0].save(update_fields=['refund_due_amount', 'refund_reason'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remboursement dû pour cette ligne'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_reason',
            field=models.CharField(blank=True, choices=[('withdrawal_support', 'Support · rétractation'), ('unused_license', 'Licence jamais activée'), ('no_waiver', 'Licence sans renonciation à la rétractation')], max_length=20, verbose_name='Motif du remboursement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant à rembourser manuellement via Stripe, somme des remboursements dus sur les lignes de la commande. Remis à zéro une fois le remboursement traité.', max_digits=10, null=True, verbose_name='Remboursement dû (somme des lignes)'),
        ),
        migrations.RunPython(backfill_item_refunds, migrations.RunPython.noop),
    ]
