# Generated by Django 5.1.15 on 2026-10-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_orderitem_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(unique=True, verbose_name="Numéro d'ordre")),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de facture')),
                ('issued_at', models.DateTimeField(verbose_name='Date de la facture')),
                ('seller', models.JSONField(verbose_name='Vendeur')),
                ('customer', models.JSONField(verbose_name='Client')),
                ('lines', models.JSONField(verbose_name='Lignes')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('total_excl_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total hors TVA')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la TVA')),
                ('total_incl_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total TVA comprise')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payments.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-sequence'],
            },
        ),
    ]
