# Generated by Django 5.1.15 on 2026-10-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Remboursement traité le'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Remboursement traité le'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant à rembourser manuellement via Stripe, somme des remboursements dus sur les lignes de la commande. Conservé une fois le remboursement traité.', max_digits=10, null=True, verbose_name='Remboursement dû (somme des lignes)'),
        ),
    ]
