# Generated by Django 6.0.4 on 2026-04-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom du menu')),
                ('slug', models.SlugField(help_text="Slug pour identifier ce menu (ex: 'main-menu')", unique=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=50, verbose_name='Titre du lien')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('open_in_new_tab', models.BooleanField(blank=True, default=False, verbose_name='Ouvrir dans un nouvel onglet')),
                ('sort_order', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menu')),
            ],
            options={
                'verbose_name': 'Élément de menu',
                'verbose_name_plural': 'Éléments de menu',
                'ordering': ['sort_order'],
            },
        ),
    ]
