# Generated by Django 6.0.3 on 2026-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(help_text="Slug pour identifier ce menu (ex: 'main-menu')"),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('slug', 'locale')},
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_core_menu'),
        ),
    ]
