# Generated by Django 5.1.15 on 2026-09-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
