# Generated by Django 6.0.3 on 2026-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menuitem_options_menuitem_locale_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_core_menuitem'),
        ),
    ]
