# Generated by Django 6.0.4 on 2026-04-27 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_uuid', models.UUIDField(unique=True, verbose_name="UUID d'Installation")),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name="Nom de l'Entreprise")),
                ('core_version', models.CharField(default='1.0.0', max_length=50, verbose_name='Version du Noyau')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Dernière Synchronisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Enregistrement")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
                'ordering': ['-last_sync'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Clé de licence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='Licence active')),
                ('activation_count', models.IntegerField(default=0, verbose_name="Nombre d'activations")),
                ('max_activations', models.IntegerField(default=1, verbose_name='Activations autorisées')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='licensing.installation', verbose_name='Installation liée')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.module', verbose_name='Module associé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'ordering': ['-created_at'],
            },
        ),
    ]
