# Generated by Django 6.0.3 on 2026-04-18 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_module_featured_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Clé de licence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='Licence active')),
                ('activation_count', models.IntegerField(default=0, verbose_name="Nombre d'activations")),
                ('max_activations', models.IntegerField(default=1, verbose_name='Activations autorisées')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.module', verbose_name='Module associé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'ordering': ['-created_at'],
            },
        ),
    ]
