# Generated by Django 6.0.3 on 2026-04-21 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='installation_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name="UUID d'Installation liée"),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Clé de licence'),
        ),
    ]
