# Generated by Django 5.1.15 on 2026-08-19 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_review_is_approved'),
        ('licensing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('activation_count__lte', models.F('max_activations'))), name='license_activation_count_lte_max_activations'),
        ),
    ]
