# Generated by Django 6.0.3 on 2026-04-21 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_license_installation_uuid_alter_license_license_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='installation_uuid',
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_uuid', models.UUIDField(unique=True, verbose_name="UUID d'Installation")),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name="Nom de l'Entreprise")),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Dernière Synchronisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Enregistrement")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
                'ordering': ['-last_sync'],
            },
        ),
        migrations.AddField(
            model_name='license',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='licensing.installation', verbose_name='Installation liée'),
        ),
    ]
