# Generated by Django 5.1.15 on 2026-09-14 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_module_support_annual_price'),
        ('licensing', '0002_license_license_activation_count_lte_max_activations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Première souscription')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernier renouvellement')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dernier montant payé')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_subscriptions', to='catalog.module', verbose_name='Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Abonnement Support',
                'verbose_name_plural': 'Abonnements Support',
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='unique_support_subscription_per_user_module')],
            },
        ),
    ]
