# Generated by Django 5.1.15 on 2026-09-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_supportsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
    ]
