# Generated by Django 6.0.3 on 2026-04-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_remove_license_installation_uuid_installation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='core_version',
            field=models.CharField(default='1.0.0', max_length=50, verbose_name='Version du Noyau'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
    ]
