# Generated by Django 5.1.15 on 2026-10-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_alter_license_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='secret_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='Empreinte du secret'),
        ),
    ]
